services:
  dev:
    build:
      context: .
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      - GOPATH=/tmp/go
      - GOCACHE=/tmp/go-cache
    volumes:
      - .:/workspace
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
