services:
  fbrl:
    build: .
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - ./data:/app/data
      - ./vision_training.py:/app/vision_training.py
      - ./fbrl:/app/fbrl
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
