model_type: letter
n_positions: 1
n_scan_glimpses: 0
n_read_glimpses: 10
read_patch_size: 12
latent_dim: 256
n_scales: 1
epochs: 50
batch_size: 52
checkpoint_interval: 10
guide_weight: 8.0
blur_sigma_ratio: 0.16
diversity_weight: 1.0
diversity_sigma: 0.1
diversity_vy: 1.0
recode_weight: 1.0
data_dir: data/letters
save_dir: data/models
